name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: vendor/bin/phpstan analyze --no-progress

    - name: Run Deptrac
      run: vendor/bin/deptrac

    - name: Run PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no

    - name: Run Sensio Security Checker
      run: vendor/bin/security-checker security:check
    
    - name: Run PHPUnit
      run: vendor/bin/phpunit
